### PR TITLE
Add the ability to use git dependencies with a fix hash

### LINKED ISSUE #3: Support Dependencies from a Branch or Specific Commit
It would be nice if we could set specific commits or branches as dependencies.  I am willing to implement this and open a PR.

### PR DESCRIPTION
**Pull request by constraintAutomaton**
Follow up of #4
closes #3

### CODE REVIEW

**Comment by constraintAutomaton** [comment]
The CI  fail at least at the moment not because of the added code

```
Neither auth token nor signing key are present.

They are looked up via $CACHIX_AUTH_TOKEN and $CACHIX_SIGNING_KEY,
and if missing also looked up from ~/.config/cachix/cachix.dhall

Read https://mycache.cachix.org for instructions how to push to your binary cache.
```

File: pkg.pl [hunk 1]
```diff
@@ -90,3 +90,9 @@
 
 git_command(git(Url, tag(Tag)), Command) :-
     git_command(git(Url, branch(Tag)), Command).
+
+git_command(git(Url, hash(Hash)), Command) :-
+    CloneCommand = ["git clone --quiet --depth 1 --single-branch ", Url, " scryer_libs/tmp "],
+    GetHashCommitCommand = [" && pushd scryer_libs/tmp && git fetch --depth 1 origin ", Hash, " && git checkout ", Hash, " && popd"],
```
Comment (bakaq) [inline pkg.pl:96]: Could you pass `--quiet` to the git commands? Both `git fetch` and `git checkout` can give some feedback output that I don't think we want polluting stdout.

**Review by bakaq — CHANGES_REQUESTED** [review]

**Comment by bakaq** [comment]
> The CI fail at least at the moment not because of the added code

Huh, I thought I configured that correctly, it was working in the `main` branch. I'll take a look...

**Comment by bakaq** [comment]
I think I fixed CI by having the part that needs secrets be a different workflow that only runs on `main`. Could you rebase this so we can check?

**Review by bakaq — APPROVED** [review]

**Comment by bakaq** [comment]
Thanks! Now just adding support for [transitive git dependencies](https://github.com/bakaq/pkg.pl/discussions/7) will already make this useful enough for non-trivial things.

**Comment by constraintAutomaton** [comment]
> Thanks! Now just adding support for [transitive git dependencies](https://github.com/bakaq/pkg.pl/discussions/7) will already make this useful enough for non-trivial things.

I think for testing and debugging #9 first might help.
